import Head from "@/app/head";
import Image from "next/image";

import Header from "@/components/Header";
import Cards from "@/components/Cards";
import Sidebar from "@/components/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar>
        <main className="bg-gray-100 min-h-screen">
          <Header />
          <Cards />
        </main>
      </Sidebar>
    </>
  );
}
