import Head from "@/app/head";
import Image from "next/image";
import { Tab } from "@headlessui/react";

import Header from "@/components/Header";
import Cards from "@/components/Cards";
import Sidebar from "@/components/Sidebar";
import Stats from "@/components/Stats";
import LineChart2 from "@/components/LineChart2";
import CardioForm from "@/components/CardioForm";
import CardioEntries3 from "@/components/CardioEntries3";
import StrengthForm from "@/components/StrengthForm";
import StrengthEntries from "@/components/StrengthEntries";
import StrengthEntryCard from "@/components/StrengthEntryCard";
import CardioEntryCard from "@/components/CardioEntryCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <main className="bg-gray-100 min-h-screen m-auto md:px-6 sm:ml-20 p-4">
        <Header />
        <>
          <div>
            <Tab.Group>
              <Tab.List className={"flex gap-4 items-center justify-start"}>
                <Tab
                  className={
                    "tab-btn text-lg bg-white shadow-lg shadow-black-500/10 px-4 py-2 cursor-pointer rounded-lg hover:bg-gray-400 focus:bg-purple-400"
                  }
                >
                  Cardio
                </Tab>
                <Tab
                  className={
                    "tab-btn text-lg bg-white shadow-lg shadow-black-500/10 px-4 py-2 cursor-pointer rounded-lg hover:bg-gray-400 focus:bg-purple-400"
                  }
                >
                  Strength
                </Tab>
              </Tab.List>

              <Tab.Panels className={" mt-6"}>
                <Tab.Panel>
                  <div className="w-full items-center md:grid md:grid-cols-5 ml-3 pb-8 pr-8 gap-x-10">
                    <LineChart2 />
                    <Stats />
                  </div>
                  <div className="bg-white border rounded-lg shadow pt-3">
                    <CardioForm />
                    <CardioEntries3 />
                  </div>
                  <CardioEntryCard />
                </Tab.Panel>

                <Tab.Panel>
                  <div className="w-full items-center sm:grid sm:grid-cols-5 ml-3 pb-8 pr-8 gap-x-10">
                    <LineChart2 />
                    <Stats />
                  </div>
                  <div className="bg-white border rounded-lg shadow pt-3">
                    <StrengthForm />
                    <StrengthEntries />
                  </div>
                  <StrengthEntryCard />
                </Tab.Panel>
              </Tab.Panels>
            </Tab.Group>
          </div>
        </>
      </main>
    </>
  );
}
