import React from "react";
import Head from "next/head";
import Header from "@/components/Header";
import Container from "@/components/Container";
import Sidebar from "@/components/Sidebar";

const dashboard = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <main className="bg-gray-100 min-h-screen m-auto md:px-6 sm:ml-20 p-4">
        <Header />
        <Container />
      </main>
    </>
  );
};

export default dashboard;
